---
title: "Untitled"
author: "Zachary Atter"
date: "19/02/2022"
output: html_document
---
##Setting up enviroment
```{r, message=FALSE}
load("NHANES0506.rda")
library(tidyverse)
# library(Hmisc)
# library(summarytools)
# library(haven)
library(labelled)
#library(cowplot)
library(kableExtra)
```

##Data exploration
```{r}
summary(dat)

#summary_df<-as_tibble(dfSummary(dat))
#print(dfSummary(dat,style='grid', plain.ascii = FALSE, graph.col = FALSE))

#describe(dat)
#notice

#Splitting into continuous and categorical, notice 
contvar<-names(dat%>%
                select_if(is.numeric))
catvar<-names(dat%>%
                select_if(is.factor))

names(dat)
#labelling variables so know what they mean easily
#no info on variables after LBXAPB

#https://www.icpsr.umich.edu/web/NACDA/search/variables?start=0&sort=STUDYID%20asc%2CDATASETID%20asc%2CSTARTPOS%20asc&STUDYQ=25504&EXTERNAL_FLAG=1&ARCHIVE=NACDA&rows=50 does not even contain any info on the later variables (I think they have been renamed)

var_label(dat) <- list(SEQN = "Respondent sequence number", RIAGENDR = "Gender",RIDAGEYR="Age at screening",RIDRETH1="Race/Ethnicity",
                       DMDEDUC2="education level- adults 20+",DMDMARTL="Martial status",INDFMINC="Annual family income",LBXGH="Glycohemoglobin (%)",BMXHT="Standing Height (cm)",BMXBMI="Body Mass Index (kg/m**2)",BMXWAIST="Waist Circumference (cm)",LBXTR="	Triglyceride (mg/dL)",LBDLDL="LDL-cholesterol (mg/dL)",LBXAPB="Apolipoprotein (B) (mg/dL)",valid_days="",valid_min="",cpm="",sed_min="minimum sedintary",light_min="minimum light exercise",active_min="minimum active exercise",sed_percent="sedintary percent",light_percent="light exercise percent",life_percent="",mod_percent="moderate exercise percent",vig_percent="vigarous exercise percent",lightlife_percent="",mvpa_percent="moderate to vigorous physical activity",active_percent="percent of physical activity",sed_bouted_30min="",num_mvpa_bouts="",num_vig_bouts="",mvpa_bouted="",vig_bouted="",guideline_min="")

#Formatting variables that should be continuous
#Used information from https://wwwn.cdc.gov/nchs/nhanes/2005-2006/DEMO_D.htm#RIDRETH1 to find labels for levels
dat<-dat%>%mutate(Gender=factor(RIAGENDR,levels=c(1,2),labels=c("Male","Female")),
                  Ethnicity=factor(RIDRETH1,levels=c(1,2,3,4,5),labels=c("Mexican American","Other Hispanic","Non-Hispanic White","Non-Hispanic Black","Other Race")),
                  Education=factor(DMDEDUC2,levels = c(1,2,3,4,5),labels=c("< 9th grade","9-11th grade","high school grade","Some College","College graduate")),
                  Married=factor(DMDMARTL,levels = c(1:6),labels=c("Married","Widowed","Divorced","Seperated","Never Married","Living with partner")))%>%
  select(-RIAGENDR,-RIDRETH1,-DMDEDUC2,-DMDMARTL)

#Creating new variable which is used to sort subjects into 3 groups depending on their Glycohemoglobin (%) we note that 49 patients had an NA reading for this measurement
dat<-dat%>%mutate(diabetes=ifelse(LBXGH>=6.5,"diabetes",ifelse(LBXGH>5.7,"pre-diabetes",ifelse(is.na(LBXGH)==F,"no diabetes",NA))))

#we create a new dataset for patients that don't have diabetes/ pre-diabetes (we have to take care as we have excluded the 49 NA values from this dataset.)
no_diabetes<-dat%>%filter(diabetes=="no diabetes")
```

#Checking for errors in data
```{r}
#Annual family income
tail(sort(dat$INDFMINC),n=15)
#Jumps from 13 to 77, should investigate this

#Body Mass Index
tail(sort(dat$BMXBMI),n=5)
#130.21 extremely high compared to others, norm max value around 60.

#Triglyceride
tail(sort(dat$LBXTR),n=10)
#Last few values very quicker increase, could look into this.

#Minimum sedintary
head(sort(dat$sed_min),n=5)
#Sudden change from 68.25 to over 153.40 in last 4 values.

tail(sort(dat$num_mvpa_bouts),n=5)
tail(sort(dat$num_vig_bouts),n=5)
tail(sort(dat$mvpa_bouted),n=5)
#Last value of all these much larger then rest of data.
```


##Inital plots to investigate variables and associations
```{r}
#denisty/histogram of response variable to see skewness of response

dens_gly<-ggplot(no_diabetes,aes(x=LBXGH))+geom_density()+
  ylab("Count")+
  xlab("Glycohemoglobin (%)")+
  theme(plot.background = element_rect(fill = "white"),panel.background = element_rect(fill = "white"),axis.line.x = element_line(color = "black"), axis.line.y = element_line(color = "black"),legend.background = element_rect(colour = "grey50"),panel.border = element_blank(),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.title=element_text(size=18,face="bold"),axis.text=element_text(size=18),axis.title.x = element_text(vjust=-0.1),legend.title=element_blank())

hist_gly<-ggplot(no_diabetes,aes(x=LBXGH))+geom_histogram(bins = 20,color="black",fill="white")+
  ylab("Count")+
  xlab("Glycohemoglobin (%)")+
  theme(plot.background = element_rect(fill = "white"),panel.background = element_rect(fill = "white"),axis.line.x = element_line(color = "black"), axis.line.y = element_line(color = "black"),legend.background = element_rect(colour = "grey50"),panel.border = element_blank(),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),axis.title=element_text(size=18,face="bold"),axis.text=element_text(size=18),axis.title.x = element_text(vjust=-0.1),legend.title=element_blank())

plot_grid(dens_gly,hist_gly)
```

```{r}
#creating 2 vectors of the continous and categorical variables
contvar<-set_names(names(dat%>%
                select_if(is.numeric)))
catvar<-set_names(names(dat%>%
                select_if(is.factor)))

#creating plots for all continous and categorical variables

#scatter plot and histograms for continous
scatter_fun<-function(x){
 ggplot(no_diabetes,aes(x=.data[[x]],y=.data[["LBXGH"]]))+geom_point()
}
eval_plots<-map(contvar,~scatter_fun(.x))
plot_grid(plotlist = eval_plots)

hist_fun<-function(x){
  ggplot(no_diabetes,aes(x=.data[[x]]))+geom_histogram(bins = 10)
}
hist_plots<-map(contvar,~hist_fun(.x))
plot_grid(plotlist = hist_plots)

#bopxplots and barcharts for categorical
box_fun<-function(x){
 ggplot(no_diabetes,aes(x=.data[[x]],y=.data[["LBXGH"]]))+geom_boxplot()+theme(axis.text.x = element_text(angle = 90))
}
eval_plots<-map(catvar,~box_fun(.x))
plot_grid(plotlist = eval_plots)

bar_func<-function(x){
  ggplot(no_diabetes,aes(x=.data[[x]],fill=.data[[x]]))+geom_bar()+theme(axis.text.x = element_text(angle = 90),legend.position = "none")
}


bar_plots<-map(catvar,~bar_func(.x))
plot_grid(plotlist = bar_plots)
```

```{r}
#splitting continous variables so easier to view (gave up on automating the process)
split_var<-split(contvar,ceiling(seq_along(contvar)/12))

scatter1<-map(as.list(names(split_var[[1]])),~scatter_fun(.x))
scatter2<-map(as.list(names(split_var[[2]])),~scatter_fun(.x))
scatter3<-map(as.list(names(split_var[[3]])),~scatter_fun(.x))

plot_grid(plotlist = scatter1)
plot_grid(plotlist = scatter2)
plot_grid(plotlist = scatter3)
```

##Correlation of continous variables
```{r}
#removing SEQN variable as is only id number
nd_filtered<-no_diabetes%>%select(-SEQN)

#using only complete observations (this will introduce bias but will allow us to see associations that should exist even with the missing data unless systematic will need to look at how data was gathered etc)
correlation<-round(cor(select_if(nd_filtered,is.numeric),use = "complete.obs"),2)
correlation

#Highlighting all elements of correlation matrix with absolute value greater than 0.5
as.data.frame(correlation)%>%
  mutate_all(~cell_spec(.x, color = ifelse(abs(.x)>0.5, "red"," black"))) %>%
  kable(escape = F) %>%
  kable_styling()

#Looking at the results we can see many of the later active variables are highly correlated as would be expected therefore we should only select 1 (need to know more about their descriptions to choose) and maybe consult with a sport scientist at which excerise category is likely to be effect at reducing A1C (ie is any exercise effective or does it need to be moderate/vigorous?)
```

##Associations of categorical variables
```{r}
#Now we look at the categorical variables (minus the one I don't know how to code so is currently a continous variable)

#seems ethnicity and education are correlated (confounded with each other), only include one
xtabs(~Ethnicity+Education,data=dat)

#looking at proptions of subjects with pre/diabetes to see if assocation exists between this and categoical variable as will give an idea of if these variables have an effect on likelihood of having high gly
diabetes<-dat%>%filter(diabetes %in% c("diabetes","pre-diabetes"))

#count grouped (do we want to do this for all categorical variables?)
ggplot(dat,aes(x=Ethnicity,fill=diabetes))+geom_bar(position = "dodge")+theme(axis.text.x = element_text(angle = 90))

prop_func<-function(x_var){
  #creating proportion dataset to feed into ggplot
  group_var<-enquo(x_var)
  merge_dat<-dat%>%group_by(!!group_var)%>%summarise(count_var=n())
  plot_data<-dat%>%group_by(!!group_var,diabetes)%>%
     summarise(count_diabetes=n())%>%
     left_join(merge_dat)%>%
     mutate(proportion=round(count_diabetes/count_var,2))
  
#reordering diabetes levels for the plot
plot_data$diabetes <- factor(plot_data$diabetes, levels = c(NA, "diabetes", "pre-diabetes","no diabetes"))

#plotting data   
ggplot(plot_data,aes(x=!!group_var,y=proportion,fill=diabetes))+
  geom_bar(stat="identity")+
  ylab("Proportion")+
  theme(axis.text.x = element_text(angle = 90))
}

#Running function on the categorical variables and putting into 2 by 2 plot to view all at once
pf_eth<-prop_func(Ethnicity)
pf_m<-prop_func(Married)
pf_g<-prop_func(Gender)
pf_ed<-prop_func(Education)

plot_grid(pf_eth,pf_m,pf_g,pf_ed)

#figure out how to get map to work at some point (if have time)
#map(noquote(catvar), ~prop_func(.x))
```



##model  fitting
#would like to know what is defined as high Gly for non-diabetic patients
```{r}
#From web search ways to lower A1C (Gylcohemoglobin) include: losing weight(in particular not being overweight-related to BMI), exercise, eat more vegtables (lower carbs)-I am going to assume this is easier for people more 'well off'

#from this I will want to include BMI, an excerise (choose MVPA arbitary until know more about them [only want to choose one as know they are highly correlated to each other]), annual family income, age (affects weight and also not include married status as confounded with this, [this may also be confounded with other variables such as exercise etc]), ethnicity as diabetic proportion seems to vary significantly with ethnicity

no_diabetes<-na.omit(no_diabetes)

#choose lm as simplist to start with
lm1<-lm(LBXGH~RIDAGEYR+mvpa_percent+INDFMINC+BMXBMI+Ethnicity,data=no_diabetes)
summary(lm1)

anova(lm1)


#Now I will perform iteration using AIC with step function to find other models to compare to my intial one to see how they vary (will then need to consider other distributions)
#start with forward iteration

#had to do this line of code to stop errors (need to understand what this is actually doing though)
no_diabetes<-na.omit(no_diabetes)

lm_intercept<-lm(LBXGH~1,data=no_diabetes)

data_all<-no_diabetes%>%select(-SEQN,-LBXGH,-diabetes)
all_var=paste(names(data_all),collapse="+")
formula_all<-paste("LBXGH~",all_var,sep="")
lm_all<-lm(formula_all,data=no_diabetes)
forward_lm<-step(lm_intercept, direction='forward', scope=formula(lm_all),trace = 0)

forward_lm$coefficients
#The forward iteration has selected age, ethnicity, BMI, education,; minimum active time and seditary bouted 30 min 

#Next do backward abd both iterations then compare to original model and evaluate what needs to be done

backward_lm<-step(lm_all,direction="backward",scope=formula(lm_all),trace=0)
backward_lm$coefficients
#going backwards includes age, BMI, Ethnicity, Education,

summary(backward_lm)

#From previous knowledge LDLC and ApoB are both molecules that are linked to cardiovascular diseases and thus makes sense to be correlated with increase in Gly (may also be correlated with BMI)

both_lm<- step(lm_intercept, direction='both', scope=formula(lm_all), trace=0)
both_lm$coefficients
#When applying iterations in both directions we find that the other lab readings are no longer significant
#Age, Ethnicity, BMI, Education, minimun physical activity and sedintary bouted 30 min (agreeing with forward iteration of step function)

#now we compare our initial model to the step function model to decide if any changes need to be made (wold proberally also want to consult an expert/ google)

lm1$coefficients
anova(lm1,forward_lm)
```
